### ISSUE TITLE
Cartas relámpago (empresa tocha)

### ISSUE THREAD

**Issue by aitortxu** [tarugoconf/unicornio_reglas#2]
Cuando se usa una carta con relámpago en el turno del otro ¿existe la posibilidad de hacerlo a medias? Es decir, si se saca un personaje con una acción lo lógico parece que no se puede ejecutar una carta "empresa tocha" que lo puede eliminar hasta que se ejecute su acción, pero el experto en juegos de mesa de la casa ha pretendido eliminarla antes de ejecutar dicha acción. Igual habría que especificar que se puede utilizar la carta relampago en el turno de otro jugador cuando el turno de este jugador termine (si es así como debería funcionar, claro).

**Comment by flipper83** [comment]
la carta entraria en mesa se hace la acción que trae la carta al ser ejecutada, y luego el otro la destruye con empresa tocha. las acciones se ejecutan cuando las cartas entran en el tablero por lo que no se puede interrumpir la acción.
